### ISSUE TITLE
Observability for streaming models

### ISSUE THREAD

**Issue by geoand** [quarkiverse/quarkus-langchain4j#1081]
### Discussed in https://github.com/quarkiverse/quarkus-langchain4j/discussions/1080

<div type='discussions-op-text'>

<sup>Originally posted by **cmasantos** November 14, 2024</sup>
Hi, I've notice that "normal" chat model produce a set of `gen_ai*` metrics. But I've been unable to use them with streaming models. Also when we use a combination of Mutiny StreamingResponseHandler I'm almost sure that it can't be done.

My question is, how can I add metrics to a streaming model even if need to instantiate them? I've found the `MetricsChatModelListener` class but I can't find a way to put it together with the streaming model interface.</div>

We should add observability for `StreamingChatLanguageModel` as well

**Comment by geoand** [comment]
@cmasantos would you be willing to contribute this feature?

**Comment by cmasantos** [comment]
> @cmasantos would you be willing to contribute this feature?

Yes, I'd like to contribute. I'll give it a try, but it will take me a while because I have no idea how extensions development work. I've got to learn that first.

**Comment by geoand** [comment]
@cmasantos do you need any help with this?

**Comment by cmasantos** [comment]
Being very open here, i didn't had time to go further than a simple exploration of the azure open ai code base since my last reply.
I did encounter a small issue here: https://github.com/cmasantos/quarkus-langchain4j/blob/7900699a261641ff08d4403a3ecb06bf9ec60929/model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/AzureOpenAiStreamingChatModel.java#L201
The response id and model name aren't available in the `onComplete` method, those values come from `dev.ai4j.openai4j.chat.ChatCompletionResponse` but the `dev.langchain4j.model.openai.OpenAiStreamingResponseBuilder` does not stores those values.
  
If you think I'm going in the right direction I can continue, I haven't looked into how this gets tests nor how this class is instantiated.

**Comment by geoand** [comment]
Thanks for the update!

I don't think that's an issue actually. I will have a quick look

**Comment by geoand** [comment]
https://github.com/quarkiverse/quarkus-langchain4j/pull/1125 takes care of this
