### ISSUE TITLE
Require`quarkus.langchain4j.openai.api-key` when starting the app

### ISSUE THREAD

**Issue by gastaldi** [quarkiverse/quarkus-langchain4j#322]
I created an application using `quarkus create app --extension=langchain4j-openai` then I ran `quarkus dev` and browsed to http://localhost:8080/q/dev-ui/io.quarkiverse.langchain4j.quarkus-langchain4j-openai/images.

Because I forgot to set the `quarkus.langchain4j.openai.api-key`, I get this strange error in the UI:

<img width="2262" alt="Screenshot 2024-02-22 at 13 38 35" src="https://github.com/quarkiverse/quarkus-langchain4j/assets/54133/99d2899e-7b5b-4412-b617-6ca22c180e51">

I see this in the logs: 
```
Caused by: dev.ai4j.openai4j.OpenAiHttpException: {
  "error": {
    "code": "invalid_api_key",
    "message": "Incorrect API key provided: dummy. You can find your API key at https://platform.openai.com/account/api-keys.",
    "param": null,
    "type": "invalid_request_error"
  }
} 
```

PS: This is also shown after I set my key (because I reached my billing limit):

```
Caused by: dev.ai4j.openai4j.OpenAiHttpException: {
  "error": {
    "code": "billing_hard_limit_reached",
    "message": "Billing hard limit has been reached",
    "param": null,
    "type": "invalid_request_error"
  }
}
```

**Comment by geoand** [comment]
Ah, we need to surface that error earlier

**Comment by jmartisk** [comment]
By the way, the useless error message (`InvocationTargetException`... stuff) will be improved by https://github.com/quarkusio/quarkus/pull/38953, the error will contain the actual exception class and message.

**Comment by gastaldi** [comment]
@jmartisk that's possible, I have zero classes in my `src/main/java`

**Comment by geoand** [comment]
> But I wonder why I get this error right during boot, while you don't:
> 
> ```
> SRCFG00014: The config property quarkus.langchain4j.openai.api-key is required but it could not be found in any config source
> ```
> 
> I guess it's because my app actually directly uses (injects) a chat model so it gets initialized eagerly

That's what I thought should have happened

**Comment by jmartisk** [comment]
Aha, this is the problem
The property has a default value of "dummy": https://github.com/quarkiverse/quarkus-langchain4j/blob/0.8.3/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/config/Langchain4jOpenAiConfig.java#L50

So when you don't specify it and you don't inject a chat model, Quarkus will accept it and boot

But if the application actually uses an (any kind of) openai model, then it will fail in the recorder, which checks that the value isn't equal to "dummy": https://github.com/quarkiverse/quarkus-langchain4j/blob/0.8.3/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/OpenAiRecorder.java#L92

I think we should make it straight-up required instead of passing a dummy default? I don't see why it could be optional.

**Comment by geoand** [comment]
That's how it used to be, however it's no longer possible with the multi model support

**Comment by geoand** [comment]
@jmartisk we will need to perform the validation done [here](https://github.com/quarkiverse/quarkus-langchain4j/blob/0.8.3/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/OpenAiRecorder.java#L91-L93) in all thee JsonRPC services.

**Comment by jmartisk** [comment]
Yeah sure. I guess I could also, at the same time, try to make the pages support selecting a model if there are more of them.
