### ISSUE TITLE
Set programmatically when to load documents in EasyRag

### ISSUE THREAD

**Issue by lordofthejars** [quarkiverse/quarkus-langchain4j#765]
Currently, when using EasyRAG, documents are read at startup time. This is great, and it should be this by default, as this makes EasyRAG Easy. Still, it would also be nice to create a new property that disables this behavior, and as developers, we can select the exact time when the documents are loaded programmatically.

For me, this is an addition that can be useful:

* In the case of extensive documents, you choose when to import them.
* In case you are using external storage and want to dynamically load documents (because they are added to the storage from another service)
* You want to test the app before and after RAG

**Comment by geoand** [comment]
cc @jmartisk

**Comment by jmartisk** [comment]
So you want to be able to turn off the automatic ingestion (which already is possible), and add some sort of programmatic trigger for it? What do you envision the "trigger" to look like? Some Quarkus-specific public static method that invokes the logic that we have in `EasyRagRecorder`?

I'm thinking that maybe such a case would be better with "regular" RAG (programmatically create and call a recursive `DocumentSplitter` and an `EmbeddingStoreIngestor` etc) instead of introducing some new (kind of dirty) API, but maybe I'm not understanding your idea properly.

**Comment by lordofthejars** [comment]
Hi, yes, the only thing I am thinking about is setting when to trigger the EasyRag ingestion. Something similar to what we can do with Flyway, to automatically run it or decide when programmatically. 

I think it is not necessary to have a static method. It can be a class that can be injected.

**Comment by jmartisk** [comment]
Ok I'll try to come up with something and let you review it
