### ISSUE TITLE
InputGuards could provide the original submitted text

### ISSUE THREAD

**Issue by lordofthejars** [quarkiverse/quarkus-langchain4j#946]
I am developing an example using InputGuards, and the AI service looks like:

```
@UserMessage("""
        Write a story about the following: {story}
        """)
    @InputGuardrails(PromptInjectionGuardrail.class)
    String writeStory(String story);
```

When I implement the Guard, I get the resolved message, but depending on the use case, you might be interested in getting the `story` value, as it is the user's input text.

**Comment by dennysfredericci** [comment]
Indeed, I am not using the guardrail because it doesn't send the raw input to PromptInjectionGuardrail.

**Comment by lordofthejars** [comment]
Yes, Guardrails is something pretty new, so they are improving as requirements come.

**Comment by geoand** [comment]
cc @cescoffier

**Comment by cescoffier** [comment]
Yes, I've discussed it with @lordofthejars. 
I think we should extend the parameters for both input and output guardrails to support the original prompts and the Map of variables.

**Comment by dennysfredericci** [comment]
Hey @cescoffier and @lordofthejars 

How do you see the "extend parameters" implemented? Here is my view, considering the @RegisterAiService annotation below:

```
@RegisterAiService
public interface ChatService {
   
    @InputGuardrails(SimpleGuardrails.class)
    @UserMessage("tell me a joke about {topic1} and {topic2} and {topic3}")
    String getJoke(String topic1, String topic2, String topic3);
}
```

We can have the _inputParameters_ in the validate method or inside of _InputGuardrailParams_ / _OutputGuardrailParams_.

I see _inputParameters_ as an array of objects because it should include all parameters from the @RegisterAiService interface. Since we have the ChatMemory inside the _InputGuardrailParams_/_OutputGuardrailParams_ parameters, we can remove the memoryId from this array.

I also considered making it an array of strings, but I am unsure how Quarkus-Langchain4j supports models with computer vision. If it does support such models, the _inputParameter_ should not be a string.

```
public interface InputGuardrail extends Guardrail<InputGuardrail.InputGuardrailParams, InputGuardrailResult> {
     .....
    default InputGuardrailResult validate(InputGuardrailParams params, Object[] inputParameters) {
        return validate(params.userMessage());
    }
```

```
public interface OutputGuardrail extends Guardrail<OutputGuardrail.OutputGuardrailParams, OutputGuardrailResult> {
     .....
    default OutputGuardrailResult validate(OutputGuardrailParams params, Object outputParameter, Object[] inputParameters) {
        return validate(params.responseFromLLM());
    }
```

Please, let me know your thoughts on this approach or if you already have something else in mind.

**Comment by cescoffier** [comment]
@dennysfredericci The guardrails API uses a `InputGuardrailParams` record for that purpose. We can add more to it without breaking. 

So, the idea is to add _properties_ to the `InputGuardrailParams` record, like _template_ (the original prompt, type to be defined) and `Map<String, Object>` for the variables.

**Comment by dennysfredericci** [comment]
@cescoffier 

Could you review my draft pull request? 👀 What are your thoughts? 

Is the test method shouldWorkWithNoUserMessage correct? 🤔

I will check why the build is failing later... 


https://github.com/quarkiverse/quarkus-langchain4j/pull/992

**Comment by dennysfredericci** [comment]
Hi @cescoffier,

You approved the PR https://github.com/quarkiverse/quarkus-langchain4j/pull/992 , but i still need to implement the output.

What do you expect for OutputGuardrail?

**Comment by cescoffier** [comment]
Exactly the same - the user prompt and variables.

**Comment by cescoffier** [comment]
Can this be closed?

**Comment by dennysfredericci** [comment]
Yep
