### ISSUE TITLE
Add Llama3.java integration 

### ISSUE THREAD

**Issue by geoand** [quarkiverse/quarkus-langchain4j#997]
Similar as Jlama

**Comment by lordofthejars** [comment]
I am interested in this, too, as this will open the door to inference `gguf` models in Java (Quarkus).

I think the best option, due to the nature of the Llama3.java, would be to create a Maven profile that, when activated, updates the local Llama3.java, so when you want to do a release of the module with a new version of Llama3, instead of modifying the pom file with a new version you enable a profile which downloads the new Llama3 and copies locally.

I know it is not perfect but the project is what it is after all.

**Comment by geoand** [comment]
We'll see how it plays out :)

**Comment by lordofthejars** [comment]
Or we can add a man in the middle aka a standalone JAR that does all these things, so from Quarkus extension, it is a JAR, but we moved the "complexity" to another project managed by us.
